spring:
  profiles:
    active: local
    include:
      - app
      - db
      - file
  devtools:
    livereload:
      enabled: true
  config:
    messages:
      basename: messages/api/message
      encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      connection-timeout: 8000
      max-lifetime: 28000

---
# local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8081

# JWT Setting
# AccessToken = Minute, RefreshToken = Day
jwt:
  secret:
    key: xxx
  access:
    token:
      expiration: 10
  refresh:
    token:
      expiration: 30

---
# dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8081


# JWT Setting
# AccessToken = Minute, RefreshToken = Day
jwt:
  secret:
    key: xxx
  access:
    token:
      expiration: 10
  refresh:
    token:
      expiration: 30

---
# prod
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8081


# JWT Setting
# AccessToken = Minute, RefreshToken = Day
jwt:
  secret:
    key: xxx
  access:
    token:
      expiration: 10
  refresh:
    token:
      expiration: 30